---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 100

    - name: "install python for Ansible."
      raw: yum -y install python

  roles:
    - configure-server

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.cxrzkkykqxtl.us-east-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: FloRo
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod